apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fppdfgen
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 70
  liveness:
    path: /is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
