apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fppdfgen
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  accessPolicy:
    inbound:
      rules:
       - application: foreldrepengesoknad-api
  image: {{image}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  port: 8080
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 1400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 128Mi
