name: Deployment pipeline dev

on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USERNAME: x-access-token
  IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: Hent tag
        run: echo "TAG=$(date "+%Y.%m.%d")-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@31f1bb4610792058145ecedb9770b0145e118a96 # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg, tag og push Docker image
        run: |
          docker build --pull --tag ${IMAGE_BASE}:${TAG} --tag ${IMAGE_BASE}:latest .
          docker push ${IMAGE_BASE} --all-tags

      - name: Lukk gamle deployment-issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['deployment']
            }).then(response => {
              response.data.forEach(issue => {
                github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
              });
            });

      -  name: Opprett deployment issue
         id: createdeployissue
         if: success()
         uses: actions/github-script@v6
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
               github.rest.issues.create( {
                 owner: context.issue.owner,
                 repo: context.issue.repo,
                 labels: ['deployment'],
                 title: 'Deploy av ${{ env.TAG }}',
                 body: '${{ github.sha }}'})
               .then(response => {
                       core.setOutput('number', response.data.number);
                });


      - name: Trigg deploy til dev-fss, dev-sbs og dev-gcp
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.NOTIFICATION }}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ steps.createdeployissue.outputs.number }} }
            github.rest.issues.createComment({...issue,
                                    title: 'Deploy av ${{ env.TAG }}',
                                    body: 'promote dev-sbs '})
            github.rest.issues.createComment({...issue,
                                    title: 'Deploy av ${{ env.TAG }}',
                                    body: '/promote dev-fss '})
            github.rest.issues.createComment({...issue,
                                    title: 'Deploy av ${{ env.TAG }}',
                                    body: '/promote dev-gcp '})


