name: Build PR or branch

on:
  pull_request:
  push:
    branches-ignore:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USERNAME: x-access-token

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v3

      - name: Kompiler
        run: docker build .
