name: Build and deploy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'dokumentasjon/**'
      - 'lokalutvikling/**'

jobs:
  build-app:
    name: Build and test
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.generate-build-version.outputs.build-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate build version
        id: generate-build-version
        run: |
          echo "build-version=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Print build version
        run: echo "Generated build-version is ${{ steps.generate-build-version.outputs.build-version }}"

      - name: Bygg og push
        if: github.ref_name == 'master'
        uses: navikt/fp-gha-workflows/.github/actions/build-push-docker-image@main
        with:
          build-version: ${{ steps.generate-build-version.outputs.build-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-image: ${{ github.ref_name == 'master' }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-dev-gcp:
    name: Deploy dev-gcp
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
    secrets: inherit

  deploy-dev-fss:
    name: Deploy dev-fss
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-fss
    secrets: inherit

  deploy-prod-gcp:
    name: Deploy prod-gcp
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app, deploy-dev-gcp]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
    secrets: inherit

  deploy-prod-fss:
    name: Deploy prod-fss
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app, deploy-dev-fss]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-fss
    secrets: inherit