name: Build and deploy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'dokumentasjon/**'
      - 'lokalutvikling/**'

jobs:
  build-app:
    name: Build and test
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.generate-build-version.outputs.build-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate build version
        id: generate-build-version
        run: |
          echo "build-version=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Print build version
        run: echo "Generated build-version is ${{ steps.generate-build-version.outputs.build-version }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          pull: true
          push: ${{ github.ref_name == 'master' }}
          tags: ghcr.io/${{ github.repository }}:${{ steps.generate-build-version.outputs.build-version }}, ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-dev-gcp:
    name: Deploy dev-gcp
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      image: ghcr.io/${{ github.repository }}:${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
    secrets: inherit

  deploy-dev-fss:
    name: Deploy dev-fss
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      image: ghcr.io/${{ github.repository }}:${{ needs.build-app.outputs.build-version }}
      cluster: dev-fss
    secrets: inherit

  deploy-prod-gcp:
    name: Deploy prod-gcp
    if: github.ref_name == 'master'
    needs: [build-app, deploy-dev-gcp]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      image: ghcr.io/${{ github.repository }}:${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
    secrets: inherit

  deploy-prod-fss:
    name: Deploy prod-fss
    if: github.ref_name == 'master'
    needs: [build-app, deploy-dev-fss]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      image: ghcr.io/${{ github.repository }}:${{ needs.build-app.outputs.build-version }}
      cluster: prod-fss
    secrets: inherit