name: Promote
on:
  repository_dispatch:
    types: [promote-command]

jobs:
  promote-dev-fss:
    name: Deploy dev-fss
    if: contains(github.event.client_payload.slash_command.args.unnamed.all, 'dev')
    uses: navikt/fp-gha-workflows/.github/workflows/deploy-app.yml@main
    with:
      issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
      environment: dev
      platform: fss
    secrets: inherit

  promote-dev-gcp:
    name: Deploy dev-gcp
    if: contains(github.event.client_payload.slash_command.args.unnamed.all, 'dev')
    uses: navikt/fp-gha-workflows/.github/workflows/deploy-app.yml@main
    with:
      issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
      environment: dev
      platform: gcp
    secrets: inherit

  promote-prod-fss:
    name: Deploy prod-fss
    needs: [promote-dev-fss, promote-dev-gcp]
    if: |
      always() &&
      contains(github.event.client_payload.slash_command.args.unnamed.all, 'prod') &&
      !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    uses: navikt/fp-gha-workflows/.github/workflows/deploy-app.yml@main
    with:
      issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
      environment: prod
      platform: fss
    secrets: inherit

  promote-prod-gcp:
    name: Deploy prod-gcp
    needs: [promote-dev-fss, promote-dev-gcp]
    if: |
      always() &&
      contains(github.event.client_payload.slash_command.args.unnamed.all, 'prod') &&
      !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    uses: navikt/fp-gha-workflows/.github/workflows/deploy-app.yml@main
    with:
      issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
      environment: prod
      platform: gcp
    secrets: inherit